import type { Metadata } from 'next'
import './globals.css'
import {Footer}  from '@/component/footer/footer';
import { Header } from '@/component/header/header';
import {Roboto,Osw,Edu} from '../Font/font';
import styles from "./styles.module.scss";
import ScrollToTopButton from '@/component/scrollBtn/scrollBtn';
// import { Provider } from 'react-redux';
// import { store } from '../app/GlobalRedux/api/store';
import { Providers } from "./GlobalRedux/provider";
import { ToastContainer } from 'react-toastify';



export const metadata: Metadata = {
  title: 'Car-shop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={`${Edu.variable} ${Roboto.variable} ${Osw.variable}`}>
        <Providers >
        <ToastContainer />
        <div className={`${styles.tsst} ${styles.backGrount}`}>
        <Header/>
        <div className={styles.container}>
        
        {children}
      
        
        </div>
        </div>
        <ScrollToTopButton/>
        <Footer/>
        </Providers>
        
      
      </body>
      
    </html>
  )
}
