export {default as Bell} from "./Bell.svg"
export {default as Char} from "./Char.svg"
export {default as  Heart} from "./Heart.svg"
export {default as  Fuel} from "./fuel.svg"
export {default as  Location} from "./location.svg"
export {default as  GearBox} from "./gear_icon.svg"
export {default as  Renge} from "./speedometer.svg"
export {default as  Clock} from "./clock.svg"
export {default as  Linkedin} from "./linkedin.svg"
export {default as  Twitter} from "./twitter.svg"
export {default as  Instagram} from "./instagram.svg"
export {default as  Facebook} from "./facebook.svg"
export {default as ChackMark} from "./checkmark.svg"


